name: Build

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env: 
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run Jest tests
        run: yarn test 
        env: 
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run Build
        run: yarn build
        env: 
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_TOKEN }}